apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
          
      containers:
      - name: jenkins
        image: gcr.io/optimistic-yeti-367811/python
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000

---

apiVersion: v1
kind: Service
metadata:
  name: python
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: jenkins

---